# Generated by Django 2.1.7 on 2020-04-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
